## Simple Left / Right Inverse

In [1]:
# Left / Right Inverse

import numpy as np

# Please replace "MatricNumber" with your actual matric number here and in the filename
def A1_MATRICNUMBER(X, y):
    # your code goes here
    # (Xt * X)
    InvXTX = np.linalg.inv(X.T @ X) 

    wLeft = InvXTX @ X.T @ y
    # wRight = X.T @ np.linalg.inv(X @ X.T) @ y

    # return in this order
    return InvXTX, wLeft

if __name__ == "__main__":
    # Example usage
    # X = np.array([[1, 1, 2],
    #             [1, 0, 6],
    #             [1, 1, 0],
    #             [1, 0, 5],
    #             [1, 1, 7]])

    X = np.array([[1, 4],
                [1, 7],
                [1, 10],
                [1, 2],
                [1, 3],
                [1, 9]])

    y = np.array([[-1],
                [-1],
                [-1],
                [1],
                [1],
                [1]])

    X_pseudo_inv, w = A1_MATRICNUMBER(X, y)

    print("Pseudo-inverse of X:")
    print(X_pseudo_inv)
    print("\nLeast squares solution w:")
    print(w)

    xTest = np.array([[1, 6]])
    print("Now the output is:")
    print(xTest @ w)
    

Pseudo-inverse of X:
[[ 0.78723404 -0.10638298]
 [-0.10638298  0.01823708]]

Least squares solution w:
[[ 0.74468085]
 [-0.12765957]]
Now the output is:
[[-0.0212766]]


## Polynomial Functions

In [5]:
# Adapted from A2 - Single polynomial thingy

import numpy as np
from numpy.linalg import inv
from sklearn.preprocessing import OneHotEncoder, PolynomialFeatures

order = 3

X = np.array([[1, 3, 4], [6, -1, 6], [5, 3, 3], [2, 1, 2]])
poly = PolynomialFeatures(order)
P = poly.fit_transform(X)
print("P: ", P)
w_poly = inv(P.T @ P) @ P.T @ y
print("w_poly: ", w_poly)

xTest = np.array([[6]])
pTest = poly.fit_transform(xTest)
predict_yp = pTest @ w_poly
print("Predicted yp: ", predict_yp)

yp_class_predict = [[1 if x >=0 else -1 ] for x in predict_yp ]
print("Predicted yp class: ", yp_class_predict)

P:  [[  1.   1.   3.   4.   1.   3.   4.   9.  12.  16.   1.   3.   4.   9.
   12.  16.  27.  36.  48.  64.]
 [  1.   6.  -1.   6.  36.  -6.  36.   1.  -6.  36. 216. -36. 216.   6.
  -36. 216.  -1.   6. -36. 216.]
 [  1.   5.   3.   3.  25.  15.  15.   9.   9.   9. 125.  75.  75.  45.
   45.  45.  27.  27.  27.  27.]
 [  1.   2.   1.   2.   4.   2.   4.   1.   2.   4.   8.   4.   8.   2.
    4.   8.   1.   2.   4.   8.]]


ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

## Correlation Coefficient

In [4]:
import numpy as np

training = np.array([[-0.709, 1.7255, 0.9539, -0.7581, -1.035, -1.049],
                     [2.8719, 1.5014, 1.8365, -0.5467, 1.8274, 0.3501],
                     [-1.8349, 0.4055, 1.0118, 0.5171, 0.7279, 1.2654],
                     [2.6354, 2.7448, 1.4616, 0.7258, -1.6893, -1.7512], 
                     [0.8206, 1.0639, 0.6895, -0.0252, 0.995, 0.6608]
                     ])

corr_x1_y = np.corrcoef(training[0], training[4])[0, 1]
corr_x2_y = np.corrcoef(training[1], training[4])[0, 1]
corr_x3_y = np.corrcoef(training[2], training[4])[0, 1]
corr_x4_y = np.corrcoef(training[3], training[4])[0, 1]

print(f'Corr between x1 and y: {corr_x1_y}')
print(f'Corr between x2 and y: {corr_x2_y}')
print(f'Corr between x3 and y: {corr_x3_y}')
print(f'Corr between x4 and y: {corr_x4_y}')
# Look at the highest ABSOLUTE correlation i.e. -0.999 > 0.5

Corr between x1 and y: 0.3543136694270562
Corr between x2 and y: 0.7542316187956285
Corr between x3 and y: -0.13588590067035158
Corr between x4 and y: 0.0871718827743873


## Gradient Descent

In [13]:
import math
learning_rate = 0.1
n = 5
w = 3 # Initialisation
cost_function = math.sin(w) ** 2
def gradient(w):
    return 2 * math.sin(w) * math.cos(w) 
    # Manually derive this

for i in range(n):
    w -= learning_rate * gradient(w)
    print("w at iteration ", i, " is ", w)

w at iteration  0  is  3.0279415498198925
w at iteration  1  is  3.0504765445441904
w at iteration  2  is  3.068599072469998
w at iteration  3  is  3.083145988671483
w at iteration  4  is  3.0948087192303437


In [3]:
import math
learning_rate = 0.03
n = 1
x = 2 # Initialisation
y = 6
z = -3
cost_function = x ** 2 * y + y ** 3 + x*y*z
def gradient_x(x, y, z):
    return 2 * x * y + x * y * z

def gradient_y(x, y, z):
    return x ** 2 + 3 * y ** 2 + x * z

def gradient_z(x, y, z):
    return x * y

for i in range(n):
    x -= learning_rate * gradient_x(x, 6, -3)
    print("x at iteration ", i, " is ", x)

for i in range(n):
    y -= learning_rate * gradient_y(2, y, -3)
    print("y at iteration ", i, " is ", y)

for i in range(n):
    z -= learning_rate * gradient_z(2, 6, z)
    print("z at iteration ", i, " is ", z)

x at iteration  0  is  2.36
y at iteration  0  is  2.8200000000000003
z at iteration  0  is  -3.36


## Regression Tree and MSE

Consider the following dataset comprising 10 datapoints: 

{x, y} = {0.2, 2.1}, {0.7, 1.5}, {1.8, 5.8}, {2.2, 6.1}, {3.7, 9.1}, {4.1, 9.5}, {4.5, 9.8}, {5.1, 12.7}, {6.3, 13.8}, {7.4, 15.9}. 

Our goal is to use a regression tree to predict y from x. Suppose at depth
1, we consider a decision threshold of 3.

In [20]:
import numpy as np

# Define the dataset
data = np.array([[0.2, 2.1],
                 [0.7, 1.5],
                 [1.8, 5.8],
                 [2.2, 6.1],
                 [3.7, 9.1],
                 [4.1, 9.5],
                 [4.5, 9.8],
                 [5.1, 12.7],
                 [6.3, 13.8],
                 [7.4, 15.9]])

# Decision threshold
threshold = 3

# Calculate MSE at the root
y_mean = np.mean(data[:, 1])
root_mse = np.mean((data[:, 1] - y_mean)**2)

# Split the data based on the decision threshold
left_data = data[data[:, 0] < threshold]
right_data = data[data[:, 0] >= threshold]

# Calculate MSE for left and right groups
left_mse = np.mean((left_data[:, 1] - np.mean(left_data[:, 1]))**2)
right_mse = np.mean((right_data[:, 1] - np.mean(right_data[:, 1]))**2)

# Compute overall MSE at depth 1
overall_mse = (left_mse * len(left_data) + right_mse * len(right_data)) / len(data)

print("MSE at the root:", round(root_mse, 3))
print("Overall MSE at depth 1:", round(overall_mse, 3))


MSE at the root: 20.638
Overall MSE at depth 1: 5.565


## Archive

In [1]:
import numpy as np
from numpy.linalg import inv
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, PolynomialFeatures

# Please replace "MatricNumber" with your actual matric number here and in the filename
def A2_MATRICNUMBER(N):

    iris = load_iris()
    X = iris['data']
    y = iris['target']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state = N) # 0.7 is test data 0.3 is training/ Right Inverse

    one_hot_encoder = OneHotEncoder(sparse_output=False) # False means array
    reshaped_ytr = y_train.reshape(len(y_train), 1) # turn it into a column
    Ytr = one_hot_encoder.fit_transform(reshaped_ytr)  

    # Do the same for the y_test data
    reshaped_yts = y_test.reshape(len(y_test), 1)
    Yts = one_hot_encoder.fit_transform(reshaped_yts)

    reg_factor = 0.0001
    Ptrain_list, Ptest_list, w_list, error_train, error_test= [], [], [], [], []

    for order in range (8):
        poly = PolynomialFeatures(degree= (order + 1) )
        P = poly.fit_transform(X_train)
        Pt = poly.fit_transform(X_test)

        Ptrain_list.append(P)
        Ptest_list.append(Pt)

        #Check for over/ underdetermined
        #Use the appropriate psuedo inverse (left/right)
        samples = P.shape[0]
        unknowns = P.shape[1]
        if samples > unknowns: # Left inverse - overdetermined
            reg_L = reg_factor * np.identity(unknowns)
            wp = inv(P.T @ P + reg_L) @ P.T @ Ytr # Primal Ridge
        else: # Right inverse - underdetermined
            reg_L2 = reg_factor * np.identity(samples)
            wp = P.T @ inv(P @ P.T + reg_L2) @ Ytr # Dual Ridge

        w_list.append(wp)

    # Get errors
    for order in range (8):
        wp = w_list[order]

        # Training
        ytr_est_p = Ptrain_list[order] @ wp
        ytr_cls_p = [ [1 if y == max(x) else 0 for y in x] for x in ytr_est_p]

        ytr1 = np.matrix(Ytr)
        ytr2 = np.matrix(ytr_cls_p)
        difference_train = np.abs(ytr1 - ytr2)

        correct_p_train = np.where(~difference_train.any(axis=1))[0]
        incorrect_p_train = len(difference_train) - len(correct_p_train)
        error_train.append(incorrect_p_train)

        # Testing
        yt_est_p = Ptest_list[order] @ wp
        yt_cls_p = [ [1 if y == max(x) else 0 for y in x] for x in yt_est_p]

        yts1 = np.matrix(Yts)
        yts2 = np.matrix(yt_cls_p)
        difference_test = np.abs(yts1 - yts2)

        correct_p_test = np.where(~difference_test.any(axis=1))[0]
        incorrect_p_test = len(difference_test) - len(correct_p_test)
        error_test.append(incorrect_p_test)
    

    error_train_array = np.array(error_train)
    error_test_array = np.array(error_test)
    # return in this order
    return X_train, y_train, X_test, y_test, Ytr, Yts, Ptrain_list, Ptest_list, w_list, error_train_array, error_test_array


In [3]:
import numpy as np

# Please replace "StudentMatriculationNumber" with your actual matric number here and in the filename
def A3_MATRICNUMBER(learning_rate, num_iters):
    # your code goes here

    # Part a
    a_out = np.zeros(num_iters)
    f1_out = np.zeros(num_iters)
    a = 2.5 # Initialisation
    a_out[0] = a - (learning_rate * 4 * a**3)
    f1_out[0] = a_out[0]**4

    # Part b
    b_out = np.zeros(num_iters)
    f2_out = np.zeros(num_iters)
    b = 0.6 # Initialisation - Radians
    b_out[0] = b - (learning_rate * 2*np.sin(b)*np.cos(b))
    f2_out[0] = np.sin(b_out[0]) ** 2

    # Part c
    c_out = np.zeros(num_iters)
    d_out = np.zeros(num_iters)
    f3_out = np.zeros(num_iters)
    c, d = 2, 3
    c_out[0] = c - (learning_rate * (5 * c**4))
    d_out[0] = d - (learning_rate * (2 * d * np.sin(d) + d**2 * np.cos(d)))
    f3_out[0] = (c_out[0]**5) + (d_out[0]**2 * np.sin(d_out[0]))

    for i in range(1, num_iters):
        aVal = a_out[i-1]
        a_out[i] = aVal - (learning_rate * 4 * aVal**3)
        f1_out[i] = a_out[i]**4

        bVal = b_out[i-1]
        b_out[i] = bVal - (learning_rate * 2*np.sin(bVal)*np.cos(bVal))
        f2_out[i] = np.sin(b_out[i]) ** 2

        cVal = c_out[i-1]
        dVal = d_out[i-1]
        c_out[i] = cVal - (learning_rate * (5 * cVal**4))
        d_out[i] = dVal - (learning_rate * (2 * dVal * np.sin(dVal) + dVal**2 * np.cos(dVal)))
        f3_out[i] = (c_out[i]**5) + (d_out[i]**2 * np.sin(d_out[i]))

    # return in this order
    return a_out, f1_out, b_out, f2_out, c_out, d_out, f3_out 

# TESTING

learning_rate = 0.1
num_iters = 5
a_out, f1_out, b_out, f2_out, c_out, d_out, f3_out = A3_MATRICNUMBER(learning_rate, num_iters)
print(f"a_out: {a_out}, \nf1_out: {f1_out}, \nb_out: {b_out}, \nf2_out: {f2_out}, \nc_out: {c_out}, \nd_out: {d_out}, \nf3_out: {f3_out}")

a_out: [-3.75000000e+00  1.73437500e+01 -2.06949554e+03  3.54530191e+09
 -1.78245948e+28], 
f1_out: [1.97753906e+002 9.04840475e+004 1.83424770e+013 1.57983925e+038
 1.00943571e+113], 
b_out: [0.50679609 0.4219224  0.34720201 0.28320925 0.22954792], 
f2_out: [0.23559234 0.16770255 0.11578239 0.07808587 0.05177323], 
c_out: [-6.00000000e+000 -6.54000000e+002 -9.14704890e+010 -3.50020924e+043
 -7.50491942e+173], 
d_out: [3.80632124 5.41623774 4.34358445 5.83403454 3.2746487 ], 
f3_out: [-7.78493691e+003 -1.19643399e+014 -6.40331702e+054 -5.25375766e+217
             -inf]


C:\Users\james\AppData\Local\Temp\ipykernel_1416\4146952937.py:57: RuntimeWarning: overflow encountered in scalar power
  f3_out[i] = (c_out[i]**5) + (d_out[i]**2 * np.sin(d_out[i]))


In [15]:
# Classifier
import numpy as np
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import OneHotEncoder
onehot_encoder=OneHotEncoder(sparse_output=False)
X = np.array([[1, 3, -2], [-4, 0, -1], [3, 1, 8], [2, 1, 6], [8, 4, 6]])
y = np.array([1, 1, 2, 3, 3])
# Now add offset to X:
X1 = np.array([[1, 1, 3, -2], 
               [1, -4, 0, -1], 
               [1, 3, 1, 8], 
               [1, 2, 1, 6], 
               [1, 8, 4, 6]])
reshaped = y.reshape(len(y), 1) # Reshape Y into a column 
Y_onehot = onehot_encoder.fit_transform(reshaped)
#print(det(X.T@X))
#print(det(X@X.T))
print(Y_onehot)
left_inv = inv(X1.T @ X1) @ (X1.T)
#right_inv = X.T @ inv(X @ X.T)
#print(right_inv)
w = left_inv @ Y_onehot
print(w)
Xnew1 = np.array([1, 1, -2, 4])
Ynew = Xnew1@w
print(Ynew)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[-0.01005025 -6.03015075  7.04020101]
 [-0.24874372 -1.74623116  1.99497487]
 [ 0.44723618  3.34170854 -3.78894472]
 [ 0.03015075  1.09045226 -1.12060302]]
[ -1.03266332 -10.09798995  12.13065327]


In [10]:
#code
import numpy as np
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures

# linear regression
m_list = [[1, 4], [1, 7], [1, 10], [1, 2], [1, 3], [1, 9]]
X = np.array(m_list)
leftinv_X = np.linalg.inv(X.T @ X) @ X.T
y = np.array([-1, -1, -1, 1, 1, 1])
w = leftinv_X.dot(y)
print(w)
predict_y = X@w
print(predict_y)
y_class_predict = [[1 if x >=0 else -1 ] for x in predict_y ]
print(y_class_predict)
Xnew = [[1, 6]]
Ynew = Xnew@w
print(Ynew)
## polynomial regression
print('poly2')

## Quadratic 2nd order poly
order = 2
origX= np.array([[4],[7], [10], [2], [3], [9]])
poly = PolynomialFeatures(order)
P = poly.fit_transform(origX)
w_poly = inv(P.T @ P) @ P.T @ y
print(w_poly)
predict_yp=P@w_poly
print(predict_yp)
yp_class_predict = [[1 if x >=0 else -1 ] for x in predict_yp ]
print(yp_class_predict)

## Order 4 poly: overdetermined
print('poly4')
order = 4
poly = PolynomialFeatures(order)
P = poly.fit_transform(origX)
w_poly = inv(P.T @ P) @P.T @ y
print(w_poly)
predict_yt=P@w_poly
print(predict_yt)
yt_class_predict = [[1 if x >=0 else -1 ] for x in predict_yt ]
print(yt_class_predict)
Xnew = [[1, 1]]
Pnew =poly.fit_transform([[6]])
print(Pnew)
Ynew_poly = Pnew@w_poly
print(Ynew_poly)

[ 0.74468085 -0.12765957]
[ 0.23404255 -0.14893617 -0.53191489  0.4893617   0.36170213 -0.40425532]
[[1], [-1], [-1], [1], [1], [-1]]
[-0.0212766]
poly2
[ 2.66875    -0.98359375  0.07109375]
[-0.128125  -0.7328125 -0.0578125  0.9859375  0.3578125 -0.425    ]
[[-1], [-1], [-1], [1], [1], [-1]]
poly4
[-11.21971831  13.52136821  -4.88054326   0.65537223  -0.02923541]
[-0.76338028 -1.11830986 -1.04225352  1.07605634  0.74647887  1.10140845]
[[-1], [-1], [-1], [1], [1], [1]]
[[1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03]]
[-2.11975855]


See matlab code below.
function RegressionTreeExam
rng(2);
x = [0.2 0.7 1.8 2.2 3.7 4.1 4.5 5.1 6.3 7.4];
y = x*2 + round(rand(1,length(x))*40)/10;
threshold = 3;
disp([x; y])
disp(['threshold = ' num2str(threshold)]);
disp(' ');
EE2211 - Introduction to Machine Learning/ Page 18
% root
root_mse = mean((y - mean(y)).^2);
disp(['root mse = ' num2str(root_mse)]);
% left x < threshold
yL = y(x < threshold);
numL = length(yL);
mse_L = mean((yL - mean(yL)).^2);
disp(['(x < threshold) mse = ' num2str(mse_L)]);
% right x > threshold
yR = y(x > threshold);
numR = length(yR);
mse_R = mean((yR - mean(yR)).^2);
disp(['(x > threshold) mse = ' num2str(mse_R)]);
% Overall MSE
overall_MSE = (mse_L * numL + mse_R * numR)/length(y);
disp(['overall mse = ' num2str(overall_MSE)]);

In [ ]:
# Chatgpt translation of the above into python: (I dont understand it)
import numpy as np

def RegressionTreeExam():
    np.random.seed(2)
    x = np.array([0.2, 0.7, 1.8, 2.2, 3.7, 4.1, 4.5, 5.1, 6.3, 7.4])
    y = x * 2 + np.round(np.random.rand(len(x)) * 40) / 10
    threshold = 3
    
    print("x:", x)
    print("y:", y)
    print("threshold =", threshold)
    print()

    # root
    root_mse = np.mean((y - np.mean(y)) ** 2)
    print("root mse =", root_mse)

    # left x < threshold
    yL = y[x < threshold]
    numL = len(yL)
    mse_L = np.mean((yL - np.mean(yL)) ** 2)
    print("(x < threshold) mse =", mse_L)

    # right x > threshold
    yR = y[x > threshold]
    numR = len(yR)
    mse_R = np.mean((yR - np.mean(yR)) ** 2)
    print("(x > threshold) mse =", mse_R)

    # Overall MSE
    overall_MSE = (mse_L * numL + mse_R * numR) / len(y)
    print("overall mse =", overall_MSE)

RegressionTreeExam()
